# Generated by Django 5.1.3 on 2025-11-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(db_index=True, max_length=500)),
                ('platform', models.CharField(choices=[('SHOPEE', 'Shopee'), ('LAZADA', 'Lazada'), ('TIKTOK', 'TikTok'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='api.product')),
            ],
            options={
                'db_table': 'product_mappings',
                'unique_together': {('platform_name', 'platform')},
            },
        ),
    ]
