# Generated by Django 5.1.3 on 2025-11-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_productmapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
    ]
