# Generated by Django 5.1.3 on 2025-12-03 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_invoiceitem_item_name_invoiceitem_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_key', models.CharField(db_index=True, max_length=255)),
                ('platform', models.CharField(choices=[('SHOPEE', 'Shopee'), ('LAZADA', 'Lazada'), ('TIKTOK', 'TikTok'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='api.product')),
            ],
            options={
                'verbose_name_plural': 'Product Aliases',
                'unique_together': {('external_key',)},
            },
        ),
    ]
