# Generated by Django 5.1.3 on 2025-12-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_productalias'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='tax_sender_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='purchase_type',
            field=models.CharField(choices=[('Credit', 'เครดิต'), ('Cash', 'เงินสด'), ('Check', 'เงินเช็ค')], default='Cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'แบบร่าง'), ('PAID', 'ชำระเงินแล้ว'), ('CANCELLED', 'ยกเลิก')], default='DRAFT', max_length=20),
        ),
    ]
