# Generated by Django 5.1.3 on 2025-12-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_purchaseorder_tax_sender_date_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_sender_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
