# Generated by Django 5.1.3 on 2025-12-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_purchaseorder_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'แบบร่าง'), ('BILLED', 'ออกใบกำกับภาษีแล้ว'), ('CANCELLED', 'ยกเลิก')], default='DRAFT'),
        ),
    ]
