# Generated by Django 5.1.3 on 2025-12-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_invoice_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'แบบร่าง'), ('BILLED', 'ออกใบกำกับภาษีแล้ว'), ('CANCELLED', 'ยกเลิก')], default='แบบร่าง'),
        ),
    ]
