# Generated by Django 5.1.3 on 2025-12-21 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_invoice_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.AddField(
            model_name='invoice',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='api.vendor'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='api.product'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='api.product'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('REPAIR_SERVICE', 'ค่าซ่อมบริการ'), ('DELIVERY', 'ค่าส่งสินค้า'), ('SALARY', 'เงินเดือนพนักงาน'), ('RENT', 'ค่าเช่า'), ('UTILITY', 'ค่าสาธารณูปโภค'), ('MARKETING', 'ค่าโฆษณา'), ('OTHER', 'อื่นๆ')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INCOME', 'รายรับ'), ('EXPENSE', 'รายจ่าย')], max_length=10),
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
