# Generated by Django 5.1.3 on 2025-12-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_invoice_customer_invoice_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
