# Generated by Django 5.1.3 on 2025-12-21 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_company_nick_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-is_active', 'name'], 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='ที่อยู่'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='อีเมล'),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='สถานะใช้งาน'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='ชื่อบริษัท'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nick_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ชื่อย่อ'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์โทร'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='เลขผู้เสียภาษี'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='api.company'),
            preserve_default=False,
        ),
    ]
