# Generated by Django 5.1.3 on 2025-12-24 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_transaction_vendor_alter_invoice_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='recipient_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'แบบร่าง'), ('BILLED', 'ออกใบกำกับภาษีแล้ว'), ('CANCELLED', 'ยกเลิก')], default='DRAFT'),
        ),
    ]
