# Generated by Django 5.1.3 on 2025-12-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_importlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='sku',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
