# Generated by Django 5.1.3 on 2025-12-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_invoiceitem_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SMARTPHONE', 'Smartphone'), ('ACCESSORY', 'Accessory'), ('TABLET', 'Tablet'), ('OTHER', 'Other')], max_length=100),
        ),
    ]
