# Generated by Django 5.1.3 on 2025-12-24 07:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='WithholdingTaxCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_number', models.CharField(default='1', max_length=20, verbose_name='เล่มที่')),
                ('cert_number', models.CharField(max_length=50, verbose_name='เลขที่')),
                ('date_issued', models.DateField(default=django.utils.timezone.now)),
                ('income_type', models.CharField(choices=[('1', 'เงินเดือน ค่าจ้าง ฯลฯ (40(1))'), ('2', 'ค่าธรรมเนียม ค่านายหน้า ฯลฯ (40(2))'), ('3', 'ค่าแห่งลิขสิทธิ์ ฯลฯ (40(3))'), ('4a', 'ดอกเบี้ย ฯลฯ (40(4)(ก))'), ('4b', 'เงินปันผล ฯลฯ (40(4)(ข))'), ('5', 'ค่าเช่า (40(5))'), ('6', 'ค่าวิชาชีพอิสระ (40(6))'), ('7', 'ค่ารับเหมา (40(7))'), ('8', 'อื่นๆ (40(8)) - โปรดระบุ')], default='8', max_length=5)),
                ('income_description', models.CharField(blank=True, max_length=200, verbose_name='ระบุประเภทเงินได้ (กรณีเลือก อื่นๆ)')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=3.0, max_digits=5)),
                ('amount_before_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='wht_certs/%Y/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wht_certs', to='api.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wht_cert', to='api.purchaseorder')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wht_certs', to='api.vendor')),
            ],
            options={
                'db_table': 'withholding_tax_certs',
                'ordering': ['-date_issued', '-cert_number'],
                'unique_together': {('company', 'book_number', 'cert_number')},
            },
        ),
    ]
