# Generated by Django 5.1.3 on 2025-12-24 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_product_category_withholdingtaxcert'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='withholdingtaxcert',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='withholdingtaxcert',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'แบบร่าง'), ('ISSUED', 'ออกใบรับแล้ว')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='withholdingtaxcert',
            name='transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wht_cert', to='api.transaction'),
        ),
        migrations.AlterField(
            model_name='withholdingtaxcert',
            name='income_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='ระบุ (ถ้าเลือกอื่นๆ)'),
        ),
        migrations.RemoveField(
            model_name='withholdingtaxcert',
            name='created_by',
        ),
    ]
