# Generated by Django 5.1.3 on 2026-03-13 13:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_withholdingtaxcert_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VatOrderBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.CharField(max_length=100, unique=True, verbose_name='เลขที่เอกสาร')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ซื้อ')),
                ('supplier_name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อผู้จำหน่าย')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vat_order_buy',
                'ordering': ['-date', '-document_no'],
            },
        ),
        migrations.CreateModel(
            name='VatOrderSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_no', models.CharField(max_length=100, unique=True, verbose_name='เลขที่เอกสาร')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่ขาย')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='ชื่อลูกค้า')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vat_order_sale',
                'ordering': ['-date', '-document_no'],
            },
        ),
        migrations.CreateModel(
            name='VatOrderBuyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Serial No')),
                ('product_name', models.CharField(max_length=500, verbose_name='ชื่อสินค้า')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='หน่วย')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคาซื้อ')),
                ('vat_company', models.CharField(blank=True, default='NONE', max_length=100, verbose_name='บริษัท VAT')),
                ('payment_method_in', models.CharField(blank=True, max_length=100, verbose_name='วิธีชำระ(เข้า)')),
                ('bank_in', models.CharField(blank=True, max_length=100, verbose_name='ธนาคาร(เข้า)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vat_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.vatorderbuy')),
            ],
            options={
                'db_table': 'vat_order_buy_items',
                'ordering': ['-vat_order__date', 'serial_no'],
            },
        ),
        migrations.CreateModel(
            name='VatOrderSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_no', models.CharField(db_index=True, max_length=100, verbose_name='Serial No')),
                ('product_name', models.CharField(max_length=500, verbose_name='ชื่อสินค้า')),
                ('unit', models.CharField(blank=True, max_length=50, verbose_name='หน่วย')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคาขาย')),
                ('payment_method_out', models.CharField(blank=True, max_length=100, verbose_name='วิธีชำระ(ออก)')),
                ('company_out', models.CharField(blank=True, max_length=100, verbose_name='บริษัท(ออก)')),
                ('tax_invoice_request', models.BooleanField(default=False, verbose_name='ขอใบกำกับภาษี')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vat_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.vatordersale')),
            ],
            options={
                'db_table': 'vat_order_sale_items',
                'ordering': ['-vat_order__date', 'serial_no'],
                'unique_together': {('vat_order', 'serial_no')},
            },
        ),
    ]
