# Generated by Django 5.1.3 on 2026-03-14 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_vatorderbuy_vatordersale_vatorderbuyitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='purchase_attachments/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.purchaseorder')),
            ],
            options={
                'db_table': 'purchase_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
