# Generated by Django 5.1.3 on 2026-03-15 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_purchaseattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='เคยพิมพ์ใบกำกับแล้ว'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='print_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='เวลาพิมพ์ล่าสุด'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_invoice_requested',
            field=models.BooleanField(default=False, verbose_name='ลูกค้าร้องขอใบกำกับภาษี'),
        ),
    ]
