# Generated by Django 5.1.3 on 2026-04-29 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_invoice_is_printed_invoice_print_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'แบบร่าง'), ('BILLED', 'ออกใบกำกับภาษีแล้ว'), ('CANCELLED', 'ยกเลิก')], default='DRAFT', max_length=20),
        ),
    ]
