# Generated by Django 5.1.3 on 2026-04-29 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_invoice_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='หัวเรื่อง')),
                ('report_type', models.CharField(choices=[('BUG', 'รายงานบั๊ก'), ('FEATURE', 'ขอฟีเจอร์ใหม่')], default='BUG', max_length=10)),
                ('status', models.CharField(choices=[('NEW', 'ใหม่'), ('IN_PROGRESS', 'กำลังดำเนินการ'), ('RESOLVED', 'แก้ไขแล้ว'), ('REJECTED', 'ปฏิเสธ')], default='NEW', max_length=20)),
                ('summary', models.TextField(verbose_name='รายละเอียด')),
                ('conversation', models.JSONField(blank=True, default=list)),
                ('degraded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bug_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bug_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BugReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='bug_reports/%Y/%m/')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bug_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.bugreport')),
            ],
            options={
                'db_table': 'bug_report_images',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
