# Generated by Django 5.1.3 on 2026-05-03 14:07

from django.db import migrations, models


def convert_po_draft_to_paid(apps, schema_editor):
    PurchaseOrder = apps.get_model('api', 'PurchaseOrder')
    PurchaseOrder.objects.filter(status='DRAFT').update(status='PAID')


def reverse_convert(apps, schema_editor):
    pass  # Cannot recover original DRAFT state — intentional


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_invoice_cancel_reason_invoice_cancelled_at_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_po_draft_to_paid, reverse_convert),
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('PAID', 'ชำระเงินแล้ว'), ('CANCELLED', 'ยกเลิก')], default='PAID', max_length=20),
        ),
    ]
