# Generated by Django 5.1.3 on 2026-05-03 15:49

from django.db import migrations, models


def convert_draft_to_unprinted(apps, schema_editor):
    Invoice = apps.get_model('api', 'Invoice')
    Invoice.objects.filter(status='DRAFT').update(status='UNPRINTED')


def reverse_convert(apps, schema_editor):
    Invoice = apps.get_model('api', 'Invoice')
    Invoice.objects.filter(status='UNPRINTED').update(status='DRAFT')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_draft_status'),
    ]

    operations = [
        migrations.RunPython(convert_draft_to_unprinted, reverse_convert),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('UNPRINTED', 'ยังไม่ได้ปริ้น'), ('BILLED', 'ออกใบกำกับภาษีแล้ว'), ('CANCELLED', 'ยกเลิก')], default='UNPRINTED', max_length=20),
        ),
    ]
