# Generated by Django 5.1.3 on 2026-05-05 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_invoice_draft_to_unprinted'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='transaction_attachments/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.transaction')),
            ],
            options={
                'db_table': 'transaction_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
