# Generated by Django 5.1.3 on 2026-05-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_transaction_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='national_id',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='เลขประจำตัวประชาชน (กรรมการ)'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='national_id',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='เลขประจำตัวประชาชน'),
        ),
        migrations.AddField(
            model_name='withholdingtaxcert',
            name='provident_fund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เงินสะสมกองทุนสำรองฯ'),
        ),
        migrations.AddField(
            model_name='withholdingtaxcert',
            name='sequence_no',
            field=models.CharField(blank=True, max_length=10, verbose_name='ลำดับที่ในแบบ'),
        ),
        migrations.AddField(
            model_name='withholdingtaxcert',
            name='social_security_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='เงินสมทบประกันสังคม'),
        ),
        migrations.AddField(
            model_name='withholdingtaxcert',
            name='social_security_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='เลขบัตรประกันสังคม'),
        ),
        migrations.AddField(
            model_name='withholdingtaxcert',
            name='xlsx_file',
            field=models.FileField(blank=True, null=True, upload_to='wht_certs/%Y/'),
        ),
    ]
