DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'NMKDEV') THEN
        CREATE USER NMKDEV WITH PASSWORD 'MAXDEV@1718';
    END IF;
END
$$;

CREATE DATABASE NMK_DB OWNER NMKDEV;
GRANT ALL PRIVILEGES ON DATABASE NMK_DB TO NMKDEV;